<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Buyers extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_buyers' => 1,
                'nama_perusahaan' => 'PT. Sukses Jaya',
                'email_perusahaan' => 'info@suksesjaya.co.id',
                'website_perusahaan' => 'www.suksesjaya.co.id',
                'hs_code' => '84713010',
                'negara_perusahaan' => 'Indonesia',
                'verif_date' => '2024-01-05 10:15:30',
            ],
            [
                'id_buyers' => 2,
                'nama_perusahaan' => 'Global Trade Ltd',
                'email_perusahaan' => 'contact@globaltrade.com',
                'website_perusahaan' => 'www.globaltrade.com',
                'hs_code' => '85423990',
                'negara_perusahaan' => 'United Kingdom',
                'verif_date' => '2023-12-20 08:30:00',
            ],
            [
                'id_buyers' => 3,
                'nama_perusahaan' => 'Tech Innovators LLC',
                'email_perusahaan' => 'info@techinnovators.com',
                'website_perusahaan' => 'www.techinnovators.com',
                'hs_code' => '84715000',
                'negara_perusahaan' => 'United States',
                'verif_date' => '2023-11-18 14:45:00',
            ],
            [
                'id_buyers' => 4,
                'nama_perusahaan' => 'Mundo Comercio S.A.',
                'email_perusahaan' => 'ventas@mundocomercio.com',
                'website_perusahaan' => 'www.mundocomercio.com',
                'hs_code' => '85258019',
                'negara_perusahaan' => 'Mexico',
                'verif_date' => '2023-10-15 16:20:00',
            ],
            [
                'id_buyers' => 5,
                'nama_perusahaan' => 'Tech Solutions GmbH',
                'email_perusahaan' => 'service@techsolutions.de',
                'website_perusahaan' => 'www.techsolutions.de',
                'hs_code' => '84733080',
                'negara_perusahaan' => 'Germany',
                'verif_date' => '2023-09-25 09:50:00',
            ],
            [
                'id_buyers' => 6,
                'nama_perusahaan' => 'Green Energy Ltd.',
                'email_perusahaan' => 'support@greenenergy.co.uk',
                'website_perusahaan' => 'www.greenenergy.co.uk',
                'hs_code' => '85023190',
                'negara_perusahaan' => 'United Kingdom',
                'verif_date' => '2023-08-12 13:05:00',
            ],
            [
                'id_buyers' => 7,
                'nama_perusahaan' => 'Kangaroo Imports Pty',
                'email_perusahaan' => 'info@kangarooimports.com.au',
                'website_perusahaan' => 'www.kangarooimports.com.au',
                'hs_code' => '84137091',
                'negara_perusahaan' => 'Australia',
                'verif_date' => '2023-07-19 17:30:00',
            ],
            [
                'id_buyers' => 8,
                'nama_perusahaan' => 'Shanghai Electronics Co.',
                'email_perusahaan' => 'sales@shanghaielectronics.cn',
                'website_perusahaan' => 'www.shanghaielectronics.cn',
                'hs_code' => '85437090',
                'negara_perusahaan' => 'China',
                'verif_date' => '2023-06-30 11:10:00',
            ],
            [
                'id_buyers' => 9,
                'nama_perusahaan' => 'Sony Corporation',
                'email_perusahaan' => 'contact@sony.co.jp',
                'website_perusahaan' => 'www.sony.co.jp',
                'hs_code' => '85299049',
                'negara_perusahaan' => 'Japan',
                'verif_date' => '2023-06-01 09:45:00',
            ],
            [
                'id_buyers' => 10,
                'nama_perusahaan' => 'Samsung Electronics',
                'email_perusahaan' => 'global@samsung.com',
                'website_perusahaan' => 'www.samsung.com',
                'hs_code' => '85258011',
                'negara_perusahaan' => 'South Korea',
                'verif_date' => '2023-05-12 15:30:00',
            ],
            [
                'id_buyers' => 11,
                'nama_perusahaan' => 'Apple Inc.',
                'email_perusahaan' => 'info@apple.com',
                'website_perusahaan' => 'www.apple.com',
                'hs_code' => '85171200',
                'negara_perusahaan' => 'United States',
                'verif_date' => '2023-04-25 14:00:00',
            ],
            [
                'id_buyers' => 12,
                'nama_perusahaan' => 'Huawei Technologies',
                'email_perusahaan' => 'sales@huawei.com',
                'website_perusahaan' => 'www.huawei.com',
                'hs_code' => '85177000',
                'negara_perusahaan' => 'China',
                'verif_date' => '2023-04-05 11:20:00',
            ],
            [
                'id_buyers' => 13,
                'nama_perusahaan' => 'Bosch GmbH',
                'email_perusahaan' => 'info@bosch.com',
                'website_perusahaan' => 'www.bosch.com',
                'hs_code' => '85044082',
                'negara_perusahaan' => 'Germany',
                'verif_date' => '2023-03-15 10:35:00',
            ],
            [
                'id_buyers' => 14,
                'nama_perusahaan' => 'Tata Motors Ltd.',
                'email_perusahaan' => 'info@tatamotors.com',
                'website_perusahaan' => 'www.tatamotors.com',
                'hs_code' => '87081090',
                'negara_perusahaan' => 'India',
                'verif_date' => '2023-03-01 08:10:00',
            ],
            [
                'id_buyers' => 15,
                'nama_perusahaan' => 'Nokia Corporation',
                'email_perusahaan' => 'contact@nokia.com',
                'website_perusahaan' => 'www.nokia.com',
                'hs_code' => '85177090',
                'negara_perusahaan' => 'Finland',
                'verif_date' => '2023-02-18 16:00:00',
            ],
            [
                'id_buyers' => 16,
                'nama_perusahaan' => 'LG Electronics',
                'email_perusahaan' => 'info@lge.com',
                'website_perusahaan' => 'www.lge.com',
                'hs_code' => '85258039',
                'negara_perusahaan' => 'South Korea',
                'verif_date' => '2023-02-05 10:25:00',
            ],
            [
                'id_buyers' => 17,
                'nama_perusahaan' => 'Siemens AG',
                'email_perusahaan' => 'support@siemens.com',
                'website_perusahaan' => 'www.siemens.com',
                'hs_code' => '85044090',
                'negara_perusahaan' => 'Germany',
                'verif_date' => '2023-01-22 12:50:00',
            ],
            [
                'id_buyers' => 18,
                'nama_perusahaan' => 'Panasonic Corporation',
                'email_perusahaan' => 'info@panasonic.com',
                'website_perusahaan' => 'www.panasonic.com',
                'hs_code' => '85299092',
                'negara_perusahaan' => 'Japan',
                'verif_date' => '2023-01-05 14:45:00',
            ],
            [
                'id_buyers' => 19,
                'nama_perusahaan' => 'Volvo Group',
                'email_perusahaan' => 'support@volvo.com',
                'website_perusahaan' => 'www.volvogroup.com',
                'hs_code' => '87081010',
                'negara_perusahaan' => 'Sweden',
                'verif_date' => '2022-12-20 15:35:00',
            ],
            [
                'id_buyers' => 20,
                'nama_perusahaan' => 'Toyota Motor Corporation',
                'email_perusahaan' => 'contact@toyota.co.jp',
                'website_perusahaan' => 'www.toyota-global.com',
                'hs_code' => '87088090',
                'negara_perusahaan' => 'Japan',
                'verif_date' => '2022-12-01 09:25:00',
            ],
            [
                'id_buyers' => 21,
                'nama_perusahaan' => 'General Electric',
                'email_perusahaan' => 'info@ge.com',
                'website_perusahaan' => 'www.ge.com',
                'hs_code' => '85044081',
                'negara_perusahaan' => 'United States',
                'verif_date' => '2022-11-15 13:30:00',
            ],
            [
                'id_buyers' => 22,
                'nama_perusahaan' => 'Nestlé S.A.',
                'email_perusahaan' => 'service@nestle.com',
                'website_perusahaan' => 'www.nestle.com',
                'hs_code' => '21069098',
                'negara_perusahaan' => 'Switzerland',
                'verif_date' => '2022-10-30 11:40:00',
            ],
            [
                'id_buyers' => 23,
                'nama_perusahaan' => 'Procter & Gamble Co.',
                'email_perusahaan' => 'contact@pg.com',
                'website_perusahaan' => 'www.pg.com',
                'hs_code' => '34013000',
                'negara_perusahaan' => 'United States',
                'verif_date' => '2022-10-10 10:15:00',
            ],
            [
                'id_buyers' => 24,
                'nama_perusahaan' => 'Unilever N.V.',
                'email_perusahaan' => 'info@unilever.com',
                'website_perusahaan' => 'www.unilever.com',
                'hs_code' => '33049900',
                'negara_perusahaan' => 'Netherlands',
                'verif_date' => '2022-09-22 14:55:00',
            ],
            [
                'id_buyers' => 25,
                'nama_perusahaan' => 'Philips Electronics',
                'email_perusahaan' => 'contact@philips.com',
                'website_perusahaan' => 'www.philips.com',
                'hs_code' => '85437090',
                'negara_perusahaan' => 'Netherlands',
                'verif_date' => '2022-08-12 08:35:00',
            ],
            [
                'id_buyers' => 26,
                'nama_perusahaan' => 'IBM Corporation',
                'email_perusahaan' => 'info@ibm.com',
                'website_perusahaan' => 'www.ibm.com',
                'hs_code' => '84714190',
                'negara_perusahaan' => 'United States',
                'verif_date' => '2022-07-25 17:45:00',
            ],
        ];

        $this->db->table('buyers')->insertBatch($data);
    }
}
