<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use \CodeIgniter\I18n\Time;

class MemberSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_member' => 1,
                'role' => 'member',
                'username' => 'rafqiputra',
                'password' => password_hash('rafqiputra', PASSWORD_DEFAULT),
                'foto_profil' => 'p1.jpg',
                'kode_referral' => 'rafqiputra',
                'popular_point' => 88888,
                'nama_perusahaan' => 'Cargill',
                'deskripsi_perusahaan' => 'Perusahaan multinasional yang bergerak di bidang agrikultur dan pangan',
                'deskripsi_perusahaan_en' => '',
                'tipe_bisnis' => 'Agribisnis',
                'tipe_bisnis_en' => '',
                'produk_utama' => 'Biji-bijian (gandum, jagung), minyak nabati, daging sapi, bahan pangan olahan, produk kakao, dan pakan ternak',
                'produk_utama_en' => '',
                'tahun_dibentuk' => 1865,
                'skala_bisnis' => 'Multinasional',
                'skala_bisnis_en' => '',
                'email_perusahaan' => 'info@cargill.com',
                'pic' => 'Jim Halpert',
                'pic_phone' => '081234567890',
                'tanggal_verifikasi' => Time::now()->subMonths(3),
                'kategori_produk' => 'Agribisnis dan Pangan',
                'kategori_produk_en' => '',
                'latitude' => -6.203635166193999,
                'longitude' => 106.81993720979659,
            ],
            [
                'id_member' => 2,
                'role' => 'member',
                'username' => 'tioramadhani',
                'password' => password_hash('tioramadhani', PASSWORD_DEFAULT),
                'foto_profil' => 'p2.jpg',
                'kode_referral' => 'tioramadhani',
                'popular_point' => 300,
                'nama_perusahaan' => 'Wilmar International',
                'deskripsi_perusahaan' => 'Salah satu produsen minyak kelapa sawit terbesar di dunia',
                'deskripsi_perusahaan_en' => '',
                'tipe_bisnis' => 'Pertanian dan Minyak Nabati',
                'tipe_bisnis_en' => '',
                'produk_utama' => 'Minyak kelapa sawit, minyak nabati (minyak kedelai, minyak bunga matahari), gula, tepung, dan produk olahan minyak nabati',
                'produk_utama_en' => '',
                'tahun_dibentuk' => 1991,
                'skala_bisnis' => 'Multinasional',
                'skala_bisnis_en' => '',
                'email_perusahaan' => 'info@wilmarint.com',
                'pic' => 'Yono Bakrie',
                'pic_phone' => '082345678901',
                'tanggal_verifikasi' => Time::now()->subMonths(2),
                'kategori_produk' => 'Agribisnis dan Minyak Nabati',
                'kategori_produk_en' => '',
                'latitude' => -6.2113708275186434,
                'longitude' => 106.83332723068169,
            ],
            [
                'id_member' => 3,
                'role' => 'member',
                'username' => 'bintangsaftar',
                'password' => password_hash('bintangsaftar', PASSWORD_DEFAULT),
                'foto_profil' => 'p3.jpg',
                'kode_referral' => 'bintangsaftar',
                'popular_point' => 288,
                'nama_perusahaan' => 'Toyota Motor Corporation',
                'deskripsi_perusahaan' => 'Produsen otomotif asal Jepang yang mengekspor kendaraan ke seluruh dunia',
                'deskripsi_perusahaan_en' => '',
                'tipe_bisnis' => 'Otomotif',
                'tipe_bisnis_en' => '',
                'produk_utama' => 'Mobil penumpang, kendaraan hybrid (Prius), kendaraan listrik, truk, dan suku cadang otomotif',
                'produk_utama_en' => '',
                'tahun_dibentuk' => 1937,
                'skala_bisnis' => 'Multinasional',
                'skala_bisnis_en' => '',
                'email_perusahaan' => 'info@toyotamc.com',
                'pic' => 'Thom Haye',
                'pic_phone' => '081567890123',
                'tanggal_verifikasi' => Time::now()->subMonths(1),
                'kategori_produk' => 'Otomotif',
                'kategori_produk_en' => '',
                'latitude' => -6.356287013125653,
                'longitude' => 107.29512436194729,
            ],
            [
                'id_member' => 4,
                'role' => 'member',
                'username' => 'rudihartono',
                'password' => password_hash('rudihartono', PASSWORD_DEFAULT),
                'foto_profil' => 'p4.jpg',
                'kode_referral' => 'rudihartono',
                'popular_point' => 243,
                'nama_perusahaan' => 'Samsung Electronics',
                'deskripsi_perusahaan' => 'Produsen elektronik dan teknologi asal Korea Selatan',
                'deskripsi_perusahaan_en' => '',
                'tipe_bisnis' => 'Elektronik dan Teknologi',
                'tipe_bisnis_en' => '',
                'produk_utama' => 'Smartphone (Galaxy series), televisi, perangkat rumah tangga (kulkas, mesin cuci), semikonduktor, dan komponen elektronik',
                'produk_utama_en' => '',
                'tahun_dibentuk' => 1969,
                'skala_bisnis' => 'Multinasional',
                'skala_bisnis_en' => '',
                'email_perusahaan' => 'info@samsung.com',
                'pic' => 'Sung Jae In',
                'pic_phone' => '081234567890',
                'tanggal_verifikasi' => Time::now()->subMonths(8),
                'kategori_produk' => 'Elektronik Konsumen dan Teknologi',
                'kategori_produk_en' => '',
                'latitude' => '',
                'longitude' => '',
            ],
            [
                'id_member' => 5,
                'role' => 'member',
                'username' => 'zainidineafi',
                'password' => password_hash('zainidineafi', PASSWORD_DEFAULT),
                'foto_profil' => 'p5.jpg',
                'kode_referral' => 'zainidineafi',
                'popular_point' => 122,
                'nama_perusahaan' => 'Vale S.A.',
                'deskripsi_perusahaan' => 'Perusahaan pertambangan asal Brasil yang mengekspor bijih besi dan nikel',
                'deskripsi_perusahaan_en' => '',
                'tipe_bisnis' => 'Pertambangan',
                'tipe_bisnis_en' => '',
                'produk_utama' => 'Bijih besi, nikel, tembaga, kobalt, batu bara, dan logam mulia lainnya',
                'produk_utama_en' => '',
                'tahun_dibentuk' => 1942,
                'skala_bisnis' => 'Multinasional',
                'skala_bisnis_en' => '',
                'email_perusahaan' => 'info@valesa.com',
                'pic' => 'Robert William',
                'pic_phone' => '081098765432',
                'tanggal_verifikasi' => Time::now()->subMonths(7),
                'kategori_produk' => 'Pertambangan dan Logam',
                'kategori_produk_en' => '',
                'latitude' => '',
                'longitude' => '',
            ],
            [
                'id_member' => 6,
                'role' => 'member',
                'username' => 'rioanugrah',
                'password' => password_hash('rioanugrah', PASSWORD_DEFAULT),
                'foto_profil' => 'p6.jpg',
                'kode_referral' => 'rioanugrah',
                'popular_point' => 223,
                'nama_perusahaan' => 'Unilever',
                'deskripsi_perusahaan' => 'Perusahaan multinasional yang bergerak di produk konsumen, seperti makanan dan perawatan tubuh',
                'deskripsi_perusahaan_en' => '',
                'tipe_bisnis' => 'Produk Konsumen',
                'tipe_bisnis_en' => '',
                'produk_utama' => 'Produk makanan (margarin, es krim), produk perawatan tubuh (sabun, sampo), produk kebersihan rumah (detergen), dan minuman ringan',
                'produk_utama_en' => '',
                'tahun_dibentuk' => 1929,
                'skala_bisnis' => 'Multinasional',
                'skala_bisnis_en' => '',
                'email_perusahaan' => 'info@unilever.com',
                'pic' => 'Lever Brothers',
                'pic_phone' => '081987654321',
                'tanggal_verifikasi' => Time::now()->subMonths(6),
                'kategori_produk' => 'Produk Konsumen',
                'kategori_produk_en' => '',
                'latitude' => '',
                'longitude' => '',
            ],
            [
                'id_member' => 7,
                'role' => 'member',
                'username' => 'rayhannash',
                'password' => password_hash('rayhannash', PASSWORD_DEFAULT),
                'foto_profil' => 'p7.jpg',
                'kode_referral' => 'rayhannash',
                'popular_point' => 101,
                'nama_perusahaan' => 'Nestlé S.A.',
                'deskripsi_perusahaan' => 'Produsen makanan dan minuman asal Swiss dengan berbagai produk global',
                'deskripsi_perusahaan_en' => '',
                'tipe_bisnis' => 'Makanan dan Minuman',
                'tipe_bisnis_en' => '',
                'produk_utama' => 'Makanan bayi, cokelat (KitKat), susu bubuk, air kemasan, kopi instan (Nescafé), dan produk nutrisi',
                'produk_utama_en' => '',
                'tahun_dibentuk' => 1867,
                'skala_bisnis' => 'Multinasional',
                'skala_bisnis_en' => '',
                'email_perusahaan' => 'info@nestle.com',
                'pic' => 'Dwight Schrute',
                'pic_phone' => '081678901234',
                'tanggal_verifikasi' => Time::now()->subMonths(5),
                'kategori_produk' => 'Makanan dan Minuman',
                'kategori_produk_en' => '',
                'latitude' => '',
                'longitude' => '',
            ],
            [
                'id_member' => 8,
                'role' => 'member',
                'username' => 'imamsyafii',
                'password' => password_hash('imamsyafii', PASSWORD_DEFAULT),
                'foto_profil' => 'p8.jpg',
                'kode_referral' => 'imamsyafii',
                'popular_point' => 98,
                'nama_perusahaan' => 'Cofco',
                'deskripsi_perusahaan' => 'Perusahaan China yang bergerak di bidang agrikultur dan pangan, mengekspor produk-produk hasil pertanian',
                'deskripsi_perusahaan_en' => '',
                'tipe_bisnis' => 'Agrikultur dan Komoditas Pangan',
                'tipe_bisnis_en' => '',
                'produk_utama' => 'Biji-bijian (gandum, jagung, kedelai), minyak nabati, daging, dan produk pangan olahan lainnya',
                'produk_utama_en' => '',
                'tahun_dibentuk' => 1949,
                'skala_bisnis' => 'Multinasional',
                'skala_bisnis_en' => '',
                'email_perusahaan' => 'info@cofco.com',
                'pic' => 'Bing Chil Ling',
                'pic_phone' => '081345678909',
                'tanggal_verifikasi' => Time::now()->subMonths(4),
                'kategori_produk' => 'Agribisnis dan Komoditas Pangan',
                'kategori_produk_en' => '',
                'latitude' => '',
                'longitude' => '',
            ]
        ];

        // Insert ke database
        $this->db->table('member')->insertBatch($data);
    }
}
