<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use \CodeIgniter\I18n\Time;

class MemberSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_member' => 2,
                'role' => 'member',
                'username' => 'dummyuser8',
                'password' => password_hash('mypassword321', PASSWORD_DEFAULT),
                'foto_profil' => 'p1.jpg',
                'kode_referral' => 'REF09876',
                'popular_point' => 300,
                'nama_perusahaan' => 'PT. Granite',
                'deskripsi_perusahaan' => 'Perusahaan yang berfokus pada solusi digital.',
                'deskripsi_perusahaan_en' => 'A company focused on digital solutions.',
                'tipe_bisnis' => 'Solusi Digital',
                'tipe_bisnis_en' => 'Digital Solutions',
                'produk_utama' => 'Aplikasi',
                'produk_utama_en' => 'Applications',
                'tahun_dibentuk' => 2020,
                'skala_bisnis' => 'Menengah',
                'skala_bisnis_en' => 'Medium',
                'email_perusahaan' => 'contact@inovasidigital.com',
                'pic' => 'Ahmad Setiawan',
                'pic_phone' => '081234567890',
                'tanggal_verifikasi' => Time::now(),
                'kategori_produk' => 'Digital',
                'kategori_produk_en' => 'Digital',
                'latitude' => -6.200000,
                'longitude' => 106.800000,
            ],
            [
                'id_member' => 3,
                'role' => 'member',
                'username' => 'dummyuser9',
                'password' => password_hash('password456', PASSWORD_DEFAULT),
                'foto_profil' => 'p2.jpg',
                'kode_referral' => 'REF12345',
                'popular_point' => 150,
                'nama_perusahaan' => 'PT. Growe',
                'deskripsi_perusahaan' => 'Penyedia solusi teknologi masa depan.',
                'deskripsi_perusahaan_en' => 'Provider of future technology solutions.',
                'tipe_bisnis' => 'Teknologi',
                'tipe_bisnis_en' => 'Technology',
                'produk_utama' => 'Robotik',
                'produk_utama_en' => 'Robotics',
                'tahun_dibentuk' => 2018,
                'skala_bisnis' => 'Lokal',
                'skala_bisnis_en' => 'Local',
                'email_perusahaan' => 'info@teknologimasa.com',
                'pic' => 'Budi Santoso',
                'pic_phone' => '082345678901',
                'tanggal_verifikasi' => Time::now()->subDays(5),
                'kategori_produk' => 'Teknologi',
                'kategori_produk_en' => 'Technology',
                'latitude' => -6.210000,
                'longitude' => 106.820000,
            ],
            [
                'id_member' => 4,
                'role' => 'member',
                'username' => 'dummyuser10',
                'password' => password_hash('securepass789', PASSWORD_DEFAULT),
                'foto_profil' => 'p3.jpg',
                'kode_referral' => 'REF67890',
                'popular_point' => 400,
                'nama_perusahaan' => 'PT. Gunung Pasirayu',
                'deskripsi_perusahaan' => 'Perusahaan yang bergerak di bidang makanan khas Nusantara.',
                'deskripsi_perusahaan_en' => 'Company specialized in traditional Indonesian cuisine.',
                'tipe_bisnis' => 'Kuliner',
                'tipe_bisnis_en' => 'Culinary',
                'produk_utama' => 'Makanan Tradisional',
                'produk_utama_en' => 'Traditional Food',
                'tahun_dibentuk' => 2015,
                'skala_bisnis' => 'Nasional',
                'skala_bisnis_en' => 'National',
                'email_perusahaan' => 'hello@kulinernusantara.com',
                'pic' => 'Rina Anwar',
                'pic_phone' => '081567890123',
                'tanggal_verifikasi' => Time::now()->subDays(15),
                'kategori_produk' => 'Kuliner',
                'kategori_produk_en' => 'Culinary',
                'latitude' => -6.250000,
                'longitude' => 106.900000,
            ],
            [
                'id_member' => 5,
                'role' => 'admin',
                'username' => 'adminuser1',
                'password' => password_hash('adminpass123', PASSWORD_DEFAULT),
                'foto_profil' => 'p4.jpg',
                'kode_referral' => 'ADMINREF01',
                'popular_point' => 600,
                'nama_perusahaan' => 'PT. INA SR12',
                'deskripsi_perusahaan' => 'Perusahaan kreatif yang bergerak di bidang periklanan.',
                'deskripsi_perusahaan_en' => 'Creative company in the advertising industry.',
                'tipe_bisnis' => 'Periklanan',
                'tipe_bisnis_en' => 'Advertising',
                'produk_utama' => 'Layanan Iklan',
                'produk_utama_en' => 'Advertising Services',
                'tahun_dibentuk' => 2012,
                'skala_bisnis' => 'Internasional',
                'skala_bisnis_en' => 'International',
                'email_perusahaan' => 'contact@mediakreatif.com',
                'pic' => 'Eko Prasetyo',
                'pic_phone' => '081234567890',
                'tanggal_verifikasi' => Time::now(),
                'kategori_produk' => 'Media',
                'kategori_produk_en' => 'Media',
                'latitude' => -6.300000,
                'longitude' => 106.850000,
            ],
            [
                'id_member' => 6,
                'role' => 'member',
                'username' => 'dummyuser12',
                'password' => password_hash('pass567890', PASSWORD_DEFAULT),
                'foto_profil' => 'p5.jpg',
                'kode_referral' => 'REF23456',
                'popular_point' => 250,
                'nama_perusahaan' => 'PT. Indolabutama',
                'deskripsi_perusahaan' => 'Perusahaan yang berfokus pada solusi energi terbarukan.',
                'deskripsi_perusahaan_en' => 'Company focused on renewable energy solutions.',
                'tipe_bisnis' => 'Energi',
                'tipe_bisnis_en' => 'Energy',
                'produk_utama' => 'Panel Surya',
                'produk_utama_en' => 'Solar Panels',
                'tahun_dibentuk' => 2019,
                'skala_bisnis' => 'Regional',
                'skala_bisnis_en' => 'Regional',
                'email_perusahaan' => 'support@energiterbarukan.com',
                'pic' => 'Siti Nurhaliza',
                'pic_phone' => '081098765432',
                'tanggal_verifikasi' => Time::now()->subDays(20),
                'kategori_produk' => 'Energi',
                'kategori_produk_en' => 'Energy',
                'latitude' => -6.220000,
                'longitude' => 106.840000,
            ],
            [
                'id_member' => 7,
                'role' => 'member',
                'username' => 'dummyuser13',
                'password' => password_hash('newpass123', PASSWORD_DEFAULT),
                'foto_profil' => 'p6.jpg',
                'kode_referral' => 'REF34567',
                'popular_point' => 200,
                'nama_perusahaan' => 'PT. Joshua',
                'deskripsi_perusahaan' => 'Perusahaan yang menyediakan solusi transportasi.',
                'deskripsi_perusahaan_en' => 'Company providing transportation solutions.',
                'tipe_bisnis' => 'Transportasi',
                'tipe_bisnis_en' => 'Transportation',
                'produk_utama' => 'Layanan Pengiriman',
                'produk_utama_en' => 'Delivery Services',
                'tahun_dibentuk' => 2021,
                'skala_bisnis' => 'Nasional',
                'skala_bisnis_en' => 'National',
                'email_perusahaan' => 'contact@solusitransport.com',
                'pic' => 'Dimas Pratama',
                'pic_phone' => '081987654321',
                'tanggal_verifikasi' => Time::now()->subDays(3),
                'kategori_produk' => 'Transportasi',
                'kategori_produk_en' => 'Transportation',
                'latitude' => -6.240000,
                'longitude' => 106.880000,
            ],
            [
                'id_member' => 8,
                'role' => 'admin',
                'username' => 'adminuser2',
                'password' => password_hash('adminpass456', PASSWORD_DEFAULT),
                'foto_profil' => 'p7.jpg',
                'kode_referral' => 'ADMINREF02',
                'popular_point' => 700,
                'nama_perusahaan' => 'PT. Kapasari',
                'deskripsi_perusahaan' => 'Agensi desain kreatif yang berfokus pada brand identity.',
                'deskripsi_perusahaan_en' => 'Creative design agency focused on brand identity.',
                'tipe_bisnis' => 'Desain',
                'tipe_bisnis_en' => 'Design',
                'produk_utama' => 'Branding',
                'produk_utama_en' => 'Branding',
                'tahun_dibentuk' => 2016,
                'skala_bisnis' => 'Internasional',
                'skala_bisnis_en' => 'International',
                'email_perusahaan' => 'info@desainkreatif.com',
                'pic' => 'Andi Saputra',
                'pic_phone' => '081678901234',
                'tanggal_verifikasi' => Time::now()->subDays(7),
                'kategori_produk' => 'Desain',
                'kategori_produk_en' => 'Design',
                'latitude' => -6.230000,
                'longitude' => 106.810000,
            ],
            [
                'id_member' => 9,
                'role' => 'member',
                'username' => 'dummyuser15',
                'password' => password_hash('userpass789', PASSWORD_DEFAULT),
                'foto_profil' => 'p8.jpg',
                'kode_referral' => 'REF45678',
                'popular_point' => 350,
                'nama_perusahaan' => 'PT. Omega',
                'deskripsi_perusahaan' => 'Perusahaan yang bergerak di bidang e-commerce.',
                'deskripsi_perusahaan_en' => 'Company specialized in e-commerce.',
                'tipe_bisnis' => 'E-Commerce',
                'tipe_bisnis_en' => 'E-Commerce',
                'produk_utama' => 'Marketplace',
                'produk_utama_en' => 'Marketplace',
                'tahun_dibentuk' => 2020,
                'skala_bisnis' => 'Lokal',
                'skala_bisnis_en' => 'Local',
                'email_perusahaan' => 'support@ecomnusantara.com',
                'pic' => 'Nina Fathurrahman',
                'pic_phone' => '081345678909',
                'tanggal_verifikasi' => Time::now()->subDays(1),
                'kategori_produk' => 'E-Commerce',
                'kategori_produk_en' => 'E-Commerce',
                'latitude' => -6.270000,
                'longitude' => 106.870000,
            ]
        ];

        // Insert ke database
        $this->db->table('member')->insertBatch($data);
    }
}
